version: 2
updates:
  - package-ecosystem: npm
    directory: /frontend
    target-branch: develop-15
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    labels:
      - dependencies
    groups:
      frontend-minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: pip
    directory: /
    target-branch: develop-15
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    target-branch: develop-15
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    labels:
      - dependencies
