export { default as ApexBar }        from './ApexBar.vue'
export { default as ApexStackedBar } from './ApexStackedBar.vue'
export { default as ApexLine }       from './ApexLine.vue'
export { default as ApexArea }       from './ApexArea.vue'
export { default as ApexDonut }      from './ApexDonut.vue'
export { default as ApexGauge }      from './ApexGauge.vue'
export { default as ApexScatter }    from './ApexScatter.vue'
export { default as ApexHeatmap }    from './ApexHeatmap.vue'
export { default as ApexCombo }      from './ApexCombo.vue'
export { default as ApexHistogram }  from './ApexHistogram.vue'
export { PALETTE, baseOptions, fmtNum, itemColors } from './apexTheme.js'
